services:
    dice-roller:
        build: .
        environment:
            - OTEL_PHP_AUTOLOAD_ENABLED=true
            - OTEL_SERVICE_NAME=dice-roller
            - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
            - OTEL_EXPORTER_OTLP_ENDPOINT=http://collector:4317
            - OTEL_TRACES_EXPORTER=otlp
            - OTEL_METRICS_EXPORTER=none
            - OTEL_LOGS_EXPORTER=console
            - OTEL_PHP_TRACES_PROCESSOR=simple
        ports:
            - "8081:80"
        depends_on:
            collector:
                condition: service_started
        volumes:
            - ./:/app

    collector:
        image: jaegertracing/all-in-one:1
        environment:
            COLLECTOR_OTLP_ENABLED: true
        ports:
            - 6831/udp
            - 6832/udp
            - 5778
            - 16686:16686 # ui
            - 4317 # OTLP over gRPC
            - 4318 # OTLP over HTTP
            - 14250
            - 14268
            - 14269
